--
-- ESQUEMA ADAPTADO AL EXAMEN
--

CREATE DATABASE IF NOT EXISTS examen;
USE examen;

CREATE TABLE CLIENTE (
    id INT AUTO_INCREMENT,
    dni VARCHAR(9),
    nombre VARCHAR(50) NOT NULL,
    email VARCHAR(50),
    usuario VARCHAR(50) NOT NULL,
    clave VARCHAR(255) NOT NULL,
    CONSTRAINT PK_CLIENTE_ID PRIMARY KEY (id),
    CONSTRAINT UK_CLIENTE_DNI UNIQUE (dni),
    CONSTRAINT UK_CLIENTE_USUARIO UNIQUE (usuario)
);

CREATE TABLE VENTA (
    id INT AUTO_INCREMENT,
    id_cliente INT,
    envio VARCHAR(200),
    facturacion VARCHAR(200) NOT NULL,
    fecha VARCHAR(200),
    metodo VARCHAR(200) NOT NULL,
    num_tarjeta VARCHAR(12),
    gastos_envio VARCHAR(100),
    CONSTRAINT PK_VENTA_ID PRIMARY KEY (id),
    CONSTRAINT FK_VENTA_ID_CLIENTE FOREIGN KEY (id_cliente) REFERENCES CLIENTE (id),
    CONSTRAINT CK_VENTA_METODO CHECK (metodo IN ('efecitvo', 'online', 'online-premium', 'Otro'))
);


CREATE TABLE REPARTIDOR (
    id INT AUTO_INCREMENT,
    dni VARCHAR(9),
    nombre VARCHAR(50) NOT NULL,
    email VARCHAR(50),
    CONSTRAINT PK_REPARTIDOR_ID PRIMARY KEY (id),
    CONSTRAINT UK_REPARTIDOR_DNI UNIQUE (dni)
);

CREATE TABLE ORDEN_TRABAJO (
    id INT AUTO_INCREMENT,
    id_repartidor INT,
    id_venta INT,
    fecha_salida VARCHAR(20),
    fecha_entrega VARCHAR(20),
    CONSTRAINT PK_ORDEN_TRABAJO_ID PRIMARY KEY (id),
    CONSTRAINT FK_ORDEN_TRABAJO_ID_REPARTIDOR FOREIGN KEY (id_repartidor) REFERENCES REPARTIDOR (id),
    CONSTRAINT FK_ORDEN_TRABAJO_ID_VENTA FOREIGN KEY (id_venta) REFERENCES VENTA (id)
);

--
-- ¡¡ ATENCIÓN !!
-- DEBIDO AL GRAN NÚMERO DE REGISTROS A GUARDAR, CONVENDRÍA HACERLO EN UNA BASE DE DATOS NO RELACIONAL.
-- CONVENDRÍA INCORPORAR UN TRIGGER QUE SE EJECUTARÁ CADA 30 MIN. POR CADA REPARTIDOR EN HORARIO DE TRABAJO.
--
CREATE TABLE GEOLOCALIZACION (
    id INT AUTO_INCREMENT,
    id_repartidor INT,
    cord_lat VARCHAR(50) NOT NULL,
    cord_lng VARCHAR(50) NOT NULL,
    fecha VARCHAR(20) NOT NULL,
    CONSTRAINT PK_GEOLOCALIZACION_ID PRIMARY KEY (id),
    CONSTRAINT FK_GEOLOCALIZACION_ID_REPARTIDOR FOREIGN KEY (id_repartidor) REFERENCES REPARTIDOR (id)
);

CREATE TABLE PLANTILLA_HORARIO (
    id INT AUTO_INCREMENT,
    lunes VARCHAR(50),
    martes VARCHAR(50),
    miercoles VARCHAR(50),
    jueves VARCHAR(50),
    viernes VARCHAR(50),
    sabado VARCHAR(50),
    domingo VARCHAR(50),
    CONSTRAINT PK_PLANTILLA_HORARIO_ID PRIMARY KEY (id)
);

CREATE TABLE HORARIO (
    id INT AUTO_INCREMENT,
    id_repartidor INT,
    id_horario INT,
    CONSTRAINT PK_HORARIO_ID PRIMARY KEY (id),
    CONSTRAINT FK_HORARIO_ID_REPARTIDOR FOREIGN KEY (id_repartidor) REFERENCES REPARTIDOR (id),
    CONSTRAINT FK_HORARIO_ID_HORARIO FOREIGN KEY (id_horario) REFERENCES PLANTILLA_HORARIO (id)
);

--
-- DATOS
--
INSERT INTO CLIENTE VALUES (1, '12345678A', 'Juan Pérez', 'juanperez@gmail.com', 'juanperez', '123456');
INSERT INTO CLIENTE VALUES (2, '98765432B', 'María González', 'mariagonzalez@gmail.com', 'mariagonzalez', '654321');

INSERT INTO VENTA VALUES (1, 1, 'C/ Amargura de examen 81', 'Juan Peréz', '11/12/2023 08:49:08', 'online-premium', 'ES98564365984', '0.00');

INSERT INTO REPARTIDOR VALUES (1, '85423657A', 'Feliciano Poco', 'fpoco@pedidos.com');

INSERT INTO ORDEN_TRABAJO VALUES (1, 1, 1, '11/12/2023 08:59:08', '11/12/2023 10:45:54');

INSERT INTO GEOLOCALIZACION VALUES (1, 1, '100.74.558.65', '54.856.854.36', '11/12/2022 09:00:00');
INSERT INTO GEOLOCALIZACION VALUES (2, 1, '100.74.100.65', '54.856.700.36', '12/12/2022 09:30:00');

INSERT INTO PLANTILLA_HORARIO VALUES (1, '19:00PM-01:00AM', '19:00PM-01:00AM', '19:00PM-01:00AM', '19:00PM-01:00AM', '19:00PM-01:00AM', null, null);

INSERT INTO HORARIO VALUES (1, 1, 1);
